import { db } from '@/db';
import { notes } from '@/db/schema';

async function main() {
    const sampleNotes = [
        {
            userId: 1,
            title: 'Data Structures Complete Notes',
            subjectName: 'Data Structures',
            semester: 3,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/1/1696838400000-data-structures-complete-notes.pdf',
            fileType: 'pdf',
            fileKey: 'notes/1/1696838400000-data-structures-complete-notes.pdf',
            fileName: 'data-structures-complete-notes.pdf',
            fileSize: 2450000,
            description: 'Comprehensive notes covering arrays, linked lists, stacks, queues, trees, and graphs with examples',
            viewsCount: 156,
            downloadsCount: 67,
            createdAt: new Date('2024-10-09').toISOString(),
            updatedAt: new Date('2024-10-09').toISOString(),
        },
        {
            userId: 2,
            title: 'DBMS Transaction Management',
            subjectName: 'Database Management',
            semester: 4,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/2/1697443200000-dbms-transaction-management.pdf',
            fileType: 'pdf',
            fileKey: 'notes/2/1697443200000-dbms-transaction-management.pdf',
            fileName: 'dbms-transaction-management.pdf',
            fileSize: 1890000,
            description: null,
            viewsCount: 134,
            downloadsCount: 54,
            createdAt: new Date('2024-10-16').toISOString(),
            updatedAt: new Date('2024-10-16').toISOString(),
        },
        {
            userId: 3,
            title: 'Operating Systems Process Scheduling',
            subjectName: 'Operating Systems',
            semester: 5,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1698048000000-operating-systems-process-scheduling.docx',
            fileType: 'docx',
            fileKey: 'notes/3/1698048000000-operating-systems-process-scheduling.docx',
            fileName: 'os-process-scheduling.docx',
            fileSize: 856000,
            description: 'Detailed notes on CPU scheduling algorithms including FCFS, SJF, Priority, and Round Robin',
            viewsCount: 178,
            downloadsCount: 72,
            createdAt: new Date('2024-10-23').toISOString(),
            updatedAt: new Date('2024-10-23').toISOString(),
        },
        {
            userId: 4,
            title: 'Computer Networks OSI Model',
            subjectName: 'Computer Networks',
            semester: 5,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/4/1698652800000-computer-networks-osi-model.pdf',
            fileType: 'pdf',
            fileKey: 'notes/4/1698652800000-computer-networks-osi-model.pdf',
            fileName: 'networks-osi-model.pdf',
            fileSize: 3120000,
            description: null,
            viewsCount: 192,
            downloadsCount: 78,
            createdAt: new Date('2024-10-30').toISOString(),
            updatedAt: new Date('2024-10-30').toISOString(),
        },
        {
            userId: 5,
            title: 'Web Development React Fundamentals',
            subjectName: 'Web Development',
            semester: 6,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/5/1699257600000-web-development-react-fundamentals.pdf',
            fileType: 'pdf',
            fileKey: 'notes/5/1699257600000-web-development-react-fundamentals.pdf',
            fileName: 'react-fundamentals.pdf',
            fileSize: 2780000,
            description: 'Complete guide to React hooks, components, state management, and modern patterns',
            viewsCount: 165,
            downloadsCount: 69,
            createdAt: new Date('2024-11-06').toISOString(),
            updatedAt: new Date('2024-11-06').toISOString(),
        },
        {
            userId: 6,
            title: 'Machine Learning Regression Analysis',
            subjectName: 'Machine Learning',
            semester: 7,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/6/1699862400000-machine-learning-regression-analysis.docx',
            fileType: 'docx',
            fileKey: 'notes/6/1699862400000-machine-learning-regression-analysis.docx',
            fileName: 'ml-regression-analysis.docx',
            fileSize: 945000,
            description: null,
            viewsCount: 143,
            downloadsCount: 61,
            createdAt: new Date('2024-11-13').toISOString(),
            updatedAt: new Date('2024-11-13').toISOString(),
        },
        {
            userId: 7,
            title: 'Software Engineering Design Patterns',
            subjectName: 'Software Engineering',
            semester: 6,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/7/1700467200000-software-engineering-design-patterns.pdf',
            fileType: 'pdf',
            fileKey: 'notes/7/1700467200000-software-engineering-design-patterns.pdf',
            fileName: 'design-patterns.pdf',
            fileSize: 4230000,
            description: 'Comprehensive guide to Singleton, Factory, Observer, Strategy, and other essential design patterns',
            viewsCount: 187,
            downloadsCount: 75,
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-11-20').toISOString(),
        },
        {
            userId: 8,
            title: 'Artificial Intelligence Search Algorithms',
            subjectName: 'Artificial Intelligence',
            semester: 7,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/8/1701072000000-artificial-intelligence-search-algorithms.pdf',
            fileType: 'pdf',
            fileKey: 'notes/8/1701072000000-artificial-intelligence-search-algorithms.pdf',
            fileName: 'ai-search-algorithms.pdf',
            fileSize: 3560000,
            description: 'Notes on BFS, DFS, A*, Hill Climbing, and Genetic Algorithms with practical examples',
            viewsCount: 171,
            downloadsCount: 68,
            createdAt: new Date('2024-11-27').toISOString(),
            updatedAt: new Date('2024-11-27').toISOString(),
        },
        {
            userId: 9,
            title: 'Cloud Computing AWS Services',
            subjectName: 'Cloud Computing',
            semester: 8,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/9/1701676800000-cloud-computing-aws-services.docx',
            fileType: 'docx',
            fileKey: 'notes/9/1701676800000-cloud-computing-aws-services.docx',
            fileName: 'aws-services.docx',
            fileSize: 1120000,
            description: null,
            viewsCount: 158,
            downloadsCount: 64,
            createdAt: new Date('2024-12-04').toISOString(),
            updatedAt: new Date('2024-12-04').toISOString(),
        },
        {
            userId: 10,
            title: 'Compiler Design Lexical Analysis',
            subjectName: 'Compiler Design',
            semester: 6,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/10/1702281600000-compiler-design-lexical-analysis.pdf',
            fileType: 'pdf',
            fileKey: 'notes/10/1702281600000-compiler-design-lexical-analysis.pdf',
            fileName: 'lexical-analysis.pdf',
            fileSize: 2190000,
            description: 'Detailed notes on tokenization, regular expressions, and finite automata',
            viewsCount: 126,
            downloadsCount: 52,
            createdAt: new Date('2024-12-11').toISOString(),
            updatedAt: new Date('2024-12-11').toISOString(),
        },
        {
            userId: 1,
            title: 'Computer Architecture MIPS Pipeline',
            subjectName: 'Computer Architecture',
            semester: 4,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/1/1702886400000-computer-architecture-mips-pipeline.pdf',
            fileType: 'pdf',
            fileKey: 'notes/1/1702886400000-computer-architecture-mips-pipeline.pdf',
            fileName: 'mips-pipeline.pdf',
            fileSize: 2850000,
            description: null,
            viewsCount: 149,
            downloadsCount: 59,
            createdAt: new Date('2024-12-18').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            userId: 2,
            title: 'Cryptography RSA Algorithm',
            subjectName: 'Cryptography',
            semester: 7,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/2/1698134400000-cryptography-rsa-algorithm.docx',
            fileType: 'docx',
            fileKey: 'notes/2/1698134400000-cryptography-rsa-algorithm.docx',
            fileName: 'rsa-algorithm.docx',
            fileSize: 678000,
            description: 'Complete explanation of RSA encryption, key generation, and security analysis',
            viewsCount: 195,
            downloadsCount: 79,
            createdAt: new Date('2024-10-24').toISOString(),
            updatedAt: new Date('2024-10-24').toISOString(),
        },
        {
            userId: 3,
            title: 'Mobile App Development Flutter Basics',
            subjectName: 'Mobile App Development',
            semester: 6,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1698739200000-mobile-app-development-flutter-basics.pdf',
            fileType: 'pdf',
            fileKey: 'notes/3/1698739200000-mobile-app-development-flutter-basics.pdf',
            fileName: 'flutter-basics.pdf',
            fileSize: 3890000,
            description: 'Introduction to Flutter widgets, state management, and navigation',
            viewsCount: 183,
            downloadsCount: 74,
            createdAt: new Date('2024-10-31').toISOString(),
            updatedAt: new Date('2024-10-31').toISOString(),
        },
        {
            userId: 4,
            title: 'Theory of Computation Turing Machines',
            subjectName: 'Theory of Computation',
            semester: 5,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/4/1699344000000-theory-of-computation-turing-machines.pdf',
            fileType: 'pdf',
            fileKey: 'notes/4/1699344000000-theory-of-computation-turing-machines.pdf',
            fileName: 'turing-machines.pdf',
            fileSize: 1670000,
            description: null,
            viewsCount: 112,
            downloadsCount: 47,
            createdAt: new Date('2024-11-07').toISOString(),
            updatedAt: new Date('2024-11-07').toISOString(),
        },
        {
            userId: 5,
            title: 'Distributed Systems Consensus Algorithms',
            subjectName: 'Distributed Systems',
            semester: 8,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/5/1699948800000-distributed-systems-consensus-algorithms.docx',
            fileType: 'docx',
            fileKey: 'notes/5/1699948800000-distributed-systems-consensus-algorithms.docx',
            fileName: 'consensus-algorithms.docx',
            fileSize: 1340000,
            description: 'Detailed notes on Paxos, Raft, and Byzantine fault tolerance',
            viewsCount: 138,
            downloadsCount: 56,
            createdAt: new Date('2024-11-14').toISOString(),
            updatedAt: new Date('2024-11-14').toISOString(),
        },
        {
            userId: 6,
            title: 'Data Mining Classification Techniques',
            subjectName: 'Data Mining',
            semester: 7,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/6/1700553600000-data-mining-classification-techniques.pdf',
            fileType: 'pdf',
            fileKey: 'notes/6/1700553600000-data-mining-classification-techniques.pdf',
            fileName: 'classification-techniques.pdf',
            fileSize: 2920000,
            description: null,
            viewsCount: 164,
            downloadsCount: 66,
            createdAt: new Date('2024-11-21').toISOString(),
            updatedAt: new Date('2024-11-21').toISOString(),
        },
        {
            userId: 7,
            title: 'Computer Graphics 3D Transformations',
            subjectName: 'Computer Graphics',
            semester: 6,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/7/1701158400000-computer-graphics-3d-transformations.pdf',
            fileType: 'pdf',
            fileKey: 'notes/7/1701158400000-computer-graphics-3d-transformations.pdf',
            fileName: '3d-transformations.pdf',
            fileSize: 4560000,
            description: 'Comprehensive guide to rotation, scaling, translation, and projection matrices',
            viewsCount: 176,
            downloadsCount: 71,
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-11-28').toISOString(),
        },
        {
            userId: 8,
            title: 'Blockchain Technology Smart Contracts',
            subjectName: 'Blockchain Technology',
            semester: 8,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/8/1701763200000-blockchain-technology-smart-contracts.docx',
            fileType: 'docx',
            fileKey: 'notes/8/1701763200000-blockchain-technology-smart-contracts.docx',
            fileName: 'smart-contracts.docx',
            fileSize: 892000,
            description: 'Introduction to Solidity, Ethereum, and smart contract development',
            viewsCount: 189,
            downloadsCount: 76,
            createdAt: new Date('2024-12-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
        },
        {
            userId: 9,
            title: 'Natural Language Processing Text Analysis',
            subjectName: 'Natural Language Processing',
            semester: 7,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/9/1702368000000-natural-language-processing-text-analysis.pdf',
            fileType: 'pdf',
            fileKey: 'notes/9/1702368000000-natural-language-processing-text-analysis.pdf',
            fileName: 'nlp-text-analysis.pdf',
            fileSize: 3340000,
            description: null,
            viewsCount: 152,
            downloadsCount: 63,
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
        },
        {
            userId: 10,
            title: 'Information Security Network Protocols',
            subjectName: 'Information Security',
            semester: 8,
            fileUrl: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/10/1702972800000-information-security-network-protocols.pdf',
            fileType: 'pdf',
            fileKey: 'notes/10/1702972800000-information-security-network-protocols.pdf',
            fileName: 'security-protocols.pdf',
            fileSize: 2610000,
            description: 'Detailed analysis of SSL/TLS, IPSec, and secure communication protocols',
            viewsCount: 167,
            downloadsCount: 70,
            createdAt: new Date('2024-12-19').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
    ];

    await db.insert(notes).values(sampleNotes);
    
    console.log('✅ Notes seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});