import { db } from '@/db';
import { notes } from '@/db/schema';

async function main() {
    const sampleNotes = [
        {
            user_id: 3,
            title: 'Complete Data Structures and Algorithms Notes',
            subject_name: 'Data Structures',
            semester: 3,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1698234567890-dsa-complete-notes.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1698234567890-dsa-complete-notes.pdf',
            file_name: 'dsa-complete-notes.pdf',
            file_size: 2456789,
            description: 'Comprehensive notes covering arrays, linked lists, trees, graphs, sorting and searching algorithms with examples and complexity analysis.',
            views_count: 156,
            downloads_count: 67,
            created_at: new Date('2024-10-15T10:30:00Z').toISOString(),
            updated_at: new Date('2024-10-15T10:30:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Database Management Systems - SQL and Normalization',
            subject_name: 'Database Management',
            semester: 4,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1699567890123-dbms-sql-normalization.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1699567890123-dbms-sql-normalization.pdf',
            file_name: 'dbms-sql-normalization.pdf',
            file_size: 1876543,
            description: null,
            views_count: 142,
            downloads_count: 58,
            created_at: new Date('2024-10-22T14:15:00Z').toISOString(),
            updated_at: new Date('2024-10-22T14:15:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Operating Systems Concepts - Process Management',
            subject_name: 'Operating Systems',
            semester: 5,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1700234567890-os-process-management.docx',
            file_type: 'docx',
            file_key: 'notes/3/1700234567890-os-process-management.docx',
            file_name: 'os-process-management.docx',
            file_size: 987654,
            description: 'Detailed notes on process scheduling, synchronization, deadlocks, and memory management techniques.',
            views_count: 178,
            downloads_count: 72,
            created_at: new Date('2024-11-05T09:45:00Z').toISOString(),
            updated_at: new Date('2024-11-05T09:45:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Computer Networks - TCP/IP Protocol Suite',
            subject_name: 'Computer Networks',
            semester: 5,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1701890123456-networks-tcpip.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1701890123456-networks-tcpip.pdf',
            file_name: 'networks-tcpip.pdf',
            file_size: 3245678,
            description: null,
            views_count: 89,
            downloads_count: 34,
            created_at: new Date('2024-11-12T16:20:00Z').toISOString(),
            updated_at: new Date('2024-11-12T16:20:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Web Development - React and Node.js Full Stack',
            subject_name: 'Web Development',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1702567890234-web-dev-fullstack.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1702567890234-web-dev-fullstack.pdf',
            file_name: 'web-dev-fullstack.pdf',
            file_size: 2987654,
            description: 'Complete guide to building full-stack applications with React frontend and Node.js backend, including REST APIs and authentication.',
            views_count: 193,
            downloads_count: 78,
            created_at: new Date('2024-11-18T11:00:00Z').toISOString(),
            updated_at: new Date('2024-11-18T11:00:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Machine Learning Fundamentals',
            subject_name: 'Machine Learning',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1703234567890-ml-fundamentals.docx',
            file_type: 'docx',
            file_key: 'notes/3/1703234567890-ml-fundamentals.docx',
            file_name: 'ml-fundamentals.docx',
            file_size: 1456789,
            description: null,
            views_count: 167,
            downloads_count: 61,
            created_at: new Date('2024-11-25T13:30:00Z').toISOString(),
            updated_at: new Date('2024-11-25T13:30:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Software Engineering - Design Patterns and SOLID Principles',
            subject_name: 'Software Engineering',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1704890123456-software-eng-patterns.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1704890123456-software-eng-patterns.pdf',
            file_name: 'software-eng-patterns.pdf',
            file_size: 2134567,
            description: 'Comprehensive notes on software design patterns, SOLID principles, and best practices for scalable application development.',
            views_count: 124,
            downloads_count: 49,
            created_at: new Date('2024-12-02T08:15:00Z').toISOString(),
            updated_at: new Date('2024-12-02T08:15:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Artificial Intelligence - Search Algorithms and Knowledge Representation',
            subject_name: 'Artificial Intelligence',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1705567890123-ai-search-algorithms.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1705567890123-ai-search-algorithms.pdf',
            file_name: 'ai-search-algorithms.pdf',
            file_size: 3567890,
            description: null,
            views_count: 98,
            downloads_count: 41,
            created_at: new Date('2024-12-08T15:45:00Z').toISOString(),
            updated_at: new Date('2024-12-08T15:45:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Cryptography and Network Security',
            subject_name: 'Cryptography',
            semester: 8,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1706234567890-crypto-network-security.docx',
            file_type: 'docx',
            file_key: 'notes/3/1706234567890-crypto-network-security.docx',
            file_name: 'crypto-network-security.docx',
            file_size: 1234567,
            description: 'Notes covering encryption algorithms, digital signatures, PKI, SSL/TLS protocols, and modern cryptographic techniques.',
            views_count: 76,
            downloads_count: 28,
            created_at: new Date('2024-12-15T10:20:00Z').toISOString(),
            updated_at: new Date('2024-12-15T10:20:00Z').toISOString(),
        },
        {
            user_id: 3,
            title: 'Theory of Computation - Automata and Formal Languages',
            subject_name: 'Theory of Computation',
            semester: 4,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1707890123456-toc-automata.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1707890123456-toc-automata.pdf',
            file_name: 'toc-automata.pdf',
            file_size: 1876543,
            description: null,
            views_count: 134,
            downloads_count: 53,
            created_at: new Date('2024-12-20T12:00:00Z').toISOString(),
            updated_at: new Date('2024-12-20T12:00:00Z').toISOString(),
        },
    ];

    await db.insert(notes).values(sampleNotes);
    
    console.log('✅ Notes seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});