import { db } from '@/db';
import { notes } from '@/db/schema';

async function main() {
    const sampleNotes = [
        {
            user_id: 1,
            title: 'Complete Data Structures Notes',
            subject_name: 'Data Structures',
            semester: 3,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/1/1697456789000-complete-data-structures-notes.pdf',
            file_type: 'pdf',
            file_key: 'notes/1/1697456789000-complete-data-structures-notes.pdf',
            file_name: 'complete-data-structures-notes.pdf',
            file_size: 2456789,
            description: 'Comprehensive notes covering arrays, linked lists, stacks, queues, trees, and graphs with detailed examples and implementations.',
            views_count: 156,
            downloads_count: 67,
            created_at: new Date('2024-10-15').toISOString(),
            updated_at: new Date('2024-10-15').toISOString(),
        },
        {
            user_id: 2,
            title: 'DBMS Normalization Chapter',
            subject_name: 'Database Management',
            semester: 4,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/2/1698567890000-dbms-normalization-chapter.pdf',
            file_type: 'pdf',
            file_key: 'notes/2/1698567890000-dbms-normalization-chapter.pdf',
            file_name: 'dbms-normalization-chapter.pdf',
            file_size: 1876543,
            description: null,
            views_count: 142,
            downloads_count: 58,
            created_at: new Date('2024-10-20').toISOString(),
            updated_at: new Date('2024-10-20').toISOString(),
        },
        {
            user_id: 3,
            title: 'Operating Systems Process Management',
            subject_name: 'Operating Systems',
            semester: 5,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1699678901000-operating-systems-process-management.docx',
            file_type: 'docx',
            file_key: 'notes/3/1699678901000-operating-systems-process-management.docx',
            file_name: 'operating-systems-process-management.docx',
            file_size: 987654,
            description: 'Detailed notes on process scheduling algorithms, deadlocks, and synchronization mechanisms with practical examples.',
            views_count: 189,
            downloads_count: 74,
            created_at: new Date('2024-10-25').toISOString(),
            updated_at: new Date('2024-10-25').toISOString(),
        },
        {
            user_id: 4,
            title: 'Computer Networks TCP/IP Protocol Suite',
            subject_name: 'Computer Networks',
            semester: 5,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/4/1700789012000-computer-networks-tcp-ip-protocol-suite.pdf',
            file_type: 'pdf',
            file_key: 'notes/4/1700789012000-computer-networks-tcp-ip-protocol-suite.pdf',
            file_name: 'computer-networks-tcp-ip-protocol-suite.pdf',
            file_size: 3234567,
            description: null,
            views_count: 167,
            downloads_count: 62,
            created_at: new Date('2024-11-01').toISOString(),
            updated_at: new Date('2024-11-01').toISOString(),
        },
        {
            user_id: 5,
            title: 'Web Development Frontend Frameworks',
            subject_name: 'Web Development',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/5/1701890123000-web-development-frontend-frameworks.pdf',
            file_type: 'pdf',
            file_key: 'notes/5/1701890123000-web-development-frontend-frameworks.pdf',
            file_name: 'web-development-frontend-frameworks.pdf',
            file_size: 2789012,
            description: 'Comprehensive guide to React, Vue, and Angular with comparison charts and best practices for modern web development.',
            views_count: 198,
            downloads_count: 79,
            created_at: new Date('2024-11-05').toISOString(),
            updated_at: new Date('2024-11-05').toISOString(),
        },
        {
            user_id: 6,
            title: 'Machine Learning Algorithms',
            subject_name: 'Machine Learning',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/6/1702901234000-machine-learning-algorithms.docx',
            file_type: 'docx',
            file_key: 'notes/6/1702901234000-machine-learning-algorithms.docx',
            file_name: 'machine-learning-algorithms.docx',
            file_size: 1456789,
            description: null,
            views_count: 134,
            downloads_count: 55,
            created_at: new Date('2024-11-10').toISOString(),
            updated_at: new Date('2024-11-10').toISOString(),
        },
        {
            user_id: 7,
            title: 'Software Engineering Design Patterns',
            subject_name: 'Software Engineering',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/7/1703912345000-software-engineering-design-patterns.pdf',
            file_type: 'pdf',
            file_key: 'notes/7/1703912345000-software-engineering-design-patterns.pdf',
            file_name: 'software-engineering-design-patterns.pdf',
            file_size: 4123456,
            description: 'Complete guide to Gang of Four design patterns with real-world examples and implementation in Java and Python.',
            views_count: 178,
            downloads_count: 71,
            created_at: new Date('2024-11-15').toISOString(),
            updated_at: new Date('2024-11-15').toISOString(),
        },
        {
            user_id: 8,
            title: 'Artificial Intelligence Search Algorithms',
            subject_name: 'Artificial Intelligence',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/8/1704923456000-artificial-intelligence-search-algorithms.pdf',
            file_type: 'pdf',
            file_key: 'notes/8/1704923456000-artificial-intelligence-search-algorithms.pdf',
            file_name: 'artificial-intelligence-search-algorithms.pdf',
            file_size: 2987654,
            description: null,
            views_count: 145,
            downloads_count: 60,
            created_at: new Date('2024-11-20').toISOString(),
            updated_at: new Date('2024-11-20').toISOString(),
        },
        {
            user_id: 9,
            title: 'Cloud Computing AWS Services Guide',
            subject_name: 'Cloud Computing',
            semester: 8,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/9/1705934567000-cloud-computing-aws-services-guide.docx',
            file_type: 'docx',
            file_key: 'notes/9/1705934567000-cloud-computing-aws-services-guide.docx',
            file_name: 'cloud-computing-aws-services-guide.docx',
            file_size: 1234567,
            description: 'Detailed overview of AWS core services including EC2, S3, Lambda, and RDS with architecture diagrams and use cases.',
            views_count: 187,
            downloads_count: 76,
            created_at: new Date('2024-11-25').toISOString(),
            updated_at: new Date('2024-11-25').toISOString(),
        },
        {
            user_id: 10,
            title: 'Compiler Design Lexical Analysis',
            subject_name: 'Compiler Design',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/10/1706945678000-compiler-design-lexical-analysis.pdf',
            file_type: 'pdf',
            file_key: 'notes/10/1706945678000-compiler-design-lexical-analysis.pdf',
            file_name: 'compiler-design-lexical-analysis.pdf',
            file_size: 3567890,
            description: null,
            views_count: 123,
            downloads_count: 51,
            created_at: new Date('2024-11-28').toISOString(),
            updated_at: new Date('2024-11-28').toISOString(),
        },
        {
            user_id: 1,
            title: 'Computer Architecture Pipeline Processing',
            subject_name: 'Computer Architecture',
            semester: 4,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/1/1707956789000-computer-architecture-pipeline-processing.pdf',
            file_type: 'pdf',
            file_key: 'notes/1/1707956789000-computer-architecture-pipeline-processing.pdf',
            file_name: 'computer-architecture-pipeline-processing.pdf',
            file_size: 2345678,
            description: 'In-depth study of instruction pipelining, hazards, and performance optimization techniques in modern processors.',
            views_count: 161,
            downloads_count: 65,
            created_at: new Date('2024-12-01').toISOString(),
            updated_at: new Date('2024-12-01').toISOString(),
        },
        {
            user_id: 2,
            title: 'Cryptography Symmetric Encryption',
            subject_name: 'Cryptography',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/2/1708967890000-cryptography-symmetric-encryption.docx',
            file_type: 'docx',
            file_key: 'notes/2/1708967890000-cryptography-symmetric-encryption.docx',
            file_name: 'cryptography-symmetric-encryption.docx',
            file_size: 876543,
            description: null,
            views_count: 152,
            downloads_count: 63,
            created_at: new Date('2024-12-03').toISOString(),
            updated_at: new Date('2024-12-03').toISOString(),
        },
        {
            user_id: 3,
            title: 'Mobile App Development Flutter Basics',
            subject_name: 'Mobile App Development',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/3/1709978901000-mobile-app-development-flutter-basics.pdf',
            file_type: 'pdf',
            file_key: 'notes/3/1709978901000-mobile-app-development-flutter-basics.pdf',
            file_name: 'mobile-app-development-flutter-basics.pdf',
            file_size: 3876543,
            description: 'Complete beginner guide to Flutter framework covering widgets, state management, and cross-platform development.',
            views_count: 195,
            downloads_count: 78,
            created_at: new Date('2024-12-05').toISOString(),
            updated_at: new Date('2024-12-05').toISOString(),
        },
        {
            user_id: 4,
            title: 'Theory of Computation Finite Automata',
            subject_name: 'Theory of Computation',
            semester: 5,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/4/1710989012000-theory-of-computation-finite-automata.pdf',
            file_type: 'pdf',
            file_key: 'notes/4/1710989012000-theory-of-computation-finite-automata.pdf',
            file_name: 'theory-of-computation-finite-automata.pdf',
            file_size: 2123456,
            description: null,
            views_count: 138,
            downloads_count: 56,
            created_at: new Date('2024-12-07').toISOString(),
            updated_at: new Date('2024-12-07').toISOString(),
        },
        {
            user_id: 5,
            title: 'Distributed Systems Consensus Algorithms',
            subject_name: 'Distributed Systems',
            semester: 8,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/5/1711990123000-distributed-systems-consensus-algorithms.docx',
            file_type: 'docx',
            file_key: 'notes/5/1711990123000-distributed-systems-consensus-algorithms.docx',
            file_name: 'distributed-systems-consensus-algorithms.docx',
            file_size: 1567890,
            description: 'Comprehensive study of Paxos and Raft consensus protocols with implementation details and use cases in distributed databases.',
            views_count: 172,
            downloads_count: 69,
            created_at: new Date('2024-12-10').toISOString(),
            updated_at: new Date('2024-12-10').toISOString(),
        },
        {
            user_id: 6,
            title: 'Data Mining Association Rules',
            subject_name: 'Data Mining',
            semester: 8,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/6/1712991234000-data-mining-association-rules.pdf',
            file_type: 'pdf',
            file_key: 'notes/6/1712991234000-data-mining-association-rules.pdf',
            file_name: 'data-mining-association-rules.pdf',
            file_size: 2654321,
            description: null,
            views_count: 147,
            downloads_count: 61,
            created_at: new Date('2024-12-12').toISOString(),
            updated_at: new Date('2024-12-12').toISOString(),
        },
        {
            user_id: 7,
            title: 'Computer Graphics 3D Transformations',
            subject_name: 'Computer Graphics',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/7/1713992345000-computer-graphics-3d-transformations.pdf',
            file_type: 'pdf',
            file_key: 'notes/7/1713992345000-computer-graphics-3d-transformations.pdf',
            file_name: 'computer-graphics-3d-transformations.pdf',
            file_size: 4567890,
            description: 'Detailed notes on 3D geometric transformations, projection techniques, and rendering pipeline with OpenGL examples.',
            views_count: 183,
            downloads_count: 73,
            created_at: new Date('2024-12-15').toISOString(),
            updated_at: new Date('2024-12-15').toISOString(),
        },
        {
            user_id: 8,
            title: 'Blockchain Technology Smart Contracts',
            subject_name: 'Blockchain Technology',
            semester: 8,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/8/1714993456000-blockchain-technology-smart-contracts.docx',
            file_type: 'docx',
            file_key: 'notes/8/1714993456000-blockchain-technology-smart-contracts.docx',
            file_name: 'blockchain-technology-smart-contracts.docx',
            file_size: 1123456,
            description: null,
            views_count: 169,
            downloads_count: 68,
            created_at: new Date('2024-12-18').toISOString(),
            updated_at: new Date('2024-12-18').toISOString(),
        },
        {
            user_id: 9,
            title: 'Natural Language Processing Text Classification',
            subject_name: 'Natural Language Processing',
            semester: 7,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/9/1715994567000-natural-language-processing-text-classification.pdf',
            file_type: 'pdf',
            file_key: 'notes/9/1715994567000-natural-language-processing-text-classification.pdf',
            file_name: 'natural-language-processing-text-classification.pdf',
            file_size: 3234567,
            description: 'Complete guide to NLP text classification techniques including bag of words, TF-IDF, and neural network approaches.',
            views_count: 191,
            downloads_count: 77,
            created_at: new Date('2024-12-20').toISOString(),
            updated_at: new Date('2024-12-20').toISOString(),
        },
        {
            user_id: 10,
            title: 'Information Security Network Security',
            subject_name: 'Information Security',
            semester: 6,
            file_url: 'https://your-project.supabase.co/storage/v1/object/public/notes/notes/10/1716995678000-information-security-network-security.pdf',
            file_type: 'pdf',
            file_key: 'notes/10/1716995678000-information-security-network-security.pdf',
            file_name: 'information-security-network-security.pdf',
            file_size: 2987654,
            description: null,
            views_count: 154,
            downloads_count: 64,
            created_at: new Date('2024-12-22').toISOString(),
            updated_at: new Date('2024-12-22').toISOString(),
        },
    ];

    await db.insert(notes).values(sampleNotes);
    
    console.log('✅ Notes seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});